### ISSUE TITLE
You got mentioned

### ISSUE THREAD

**Issue by ghost** [martinchristen/pyRT#15]
https://habrahabr.ru/company/JetBrains/blog/316068/
habrahabr.ru - most popular website for IT specialists in CIS
![image](https://cloud.githubusercontent.com/assets/21169548/20708619/d872a732-b641-11e6-9cbf-2869fd24808b.png)

**Comment by martinchristen** [comment]
same on: https://www.jetbrains.com/pycharm/whatsnew/

**Comment by ghost** [comment]
@martinchristen it's basically because most part of employees at JetBrains are from CIS
